/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 DamagedHelmet.gltf
*/
import * as THREE from "three";
import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { easing } from "maath";

export function Model(props) {
  const mesh = useRef();

  const { nodes } = useGLTF("./suzanne.glb");
  const [dummy] = useState(() => new THREE.Object3D());
  useFrame((state, dt) => {
    dummy.lookAt(state.pointer.x, state.pointer.y, 1);
    easing.dampQ(mesh.current.quaternion, dummy.quaternion, 0.15, dt);
  });

  return (
    <group {...props} dispose={null}>
      <mesh ref={mesh} scale={1} geometry={nodes.Suzanne.geometry} {...props}>
        <meshNormalMaterial />
      </mesh>
    </group>
  );
}
